cache:
  bundler: true
  directories:
    - node_modules # NPM packages

language: node_js
node_js:
  - "6.11.1"


script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: deploy release
      node_js: "6.11.1"
      script: echo "Deploying to firebase ..."
      deploy:
        - provider: script
          script: cd functions
                  npm install -g firebase-tools
                  npm install

                  echo $JSON >> serviceAccountKey.json

                  firebase deploy --token $FIREBASE_TOKEN
          on: master