language: node_js
node_js:
  - "6.11.1"

branches:
  only:
    - development

before_script:
  - cd functions
  - npm install -g firebase-tools
  - npm install
  - echo $JSON >> serviceAccountKey.json
