cache:
  bundler: true
  directories:
    - functions/node_modules # NPM packages

language: node_js
node_js:
  - "6.11.1"


script: echo "Running tests against $(node -v) ..."

jobs:
  include:
    - stage: deploy release
      node_js: "6.11.1"
      script: echo "Deploying to firebase ..."
      deploy:
        - provider: script
          script: deploy.sh JSON=$JSON token=$FIREBASE_TOKEN
          on: master