language: node_js
node_js:
  - "6.11.1"

branches:
  only:
    - master

before_script:
  - cd functions
  - npm install -g firebase-tools
  - npm install

script: 
 - firebase deploy --token $FIREBASE_TOKEN