runtime: python27
threadsafe: true
api_version: 1
basic_scaling:
  max_instances: 2


#[START_EXCLUDE]
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?setuptools/script \(dev\).tmpl$
#[END_EXCLUDE]

handlers:
#  Everything goes to main.py
  - url: .*
    script: main.app
